id: A88634D84
title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female Awareness-Holder
  (Yumka)'
type: translation
pechas:
- IF609BFFF
- I6D56FE59
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:01.113898
  last_modified_at: 2023-01-04 12:43:01.113920
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IF609BFFF/4BB8: 1C58
  I6D56FE59/2A6A: 1C58
